SAMPS = "CHM13 GM24143 GM24149 GM24385 HG00733 HG01109 HG01243 HG02055 HG02080 HG02723 HG03098 HG03492".split()

include: "rules/01_subset_chr.smk"
include: "rules/02_call_variants.smk"
include: "rules/03_construct_graph.smk"

configfile: "rules/config.yaml"

rule all:
    input:
        expand("alignments/{sample}.gam", sample=config["samples"])


def get_samples(wildcards):
    return config["samples"][wildcards.sample]


rule vg_map:
    input:
        forward = "reads/HG002_HiSeq300x_fastq/{library}/Project_RM8391_RM8392/{sample}/{lane}_R1_{number}.fastq.gz",
        reverse = "reads/HG002_HiSeq300x_fastq/{library}/Project_RM8391_RM8392/{sample}/{lane}_R2_{number}.fastq.gz",
        xg = "graph/chr10.asm20.xg",
        gcsa = "graph/chr10.asm20.gcsa"
    output:
        "alignments/{library}.{sample}.{lane}.{number}.gam"
    threads: 7
    shell:
        "vg map -t {threads} -x {input.xg} -g {input.gcsa} -f {input.forward} -f {input.reverse} > {output}"
